### PR TITLE
Initial Travis setup

### PR DESCRIPTION
**Pull request by rgbkrk**
This uses https://github.com/craigcitro/r-travis to setup Travis builds for rzmq. You'll need to add the actual integration with Travis after merge.

### CODE REVIEW

**Comment by armstrtw** [comment]
could you walk me through this?  perhaps via email? or just send a link to your favorite documentation for travis? thx.

**Comment by rgbkrk** [comment]
Actually, it looks like [Travis now supports R directly](https://docs.travis-ci.com/user/languages/r/). I'll have to update this PR now.

**Comment by armstrtw** [comment]
Right.  We have this working for Rblpapi, so I can just copy the config over changing the account...  I assume there is some account that needs to exist over at the Travis site.

**Comment by rgbkrk** [comment]
Travis is tied to the owner of the repo. Since yours is under a user, it's under your control to enable within

https://travis-ci.org/profile/armstrtw

Here's the [starter guide that Travis offers](https://docs.travis-ci.com/user/for-beginners), though you'll probably be able to [flip a switch on your profile](https://travis-ci.org/profile/armstrtw) that looks like this:

screenshot 2015-12-22 09 09 44

to this:

screenshot 2015-12-22 09 10 27

**Comment by rgbkrk** [comment]
I'm clearing out all my old PRs. Feel free to revisit if someone wants it.

**Pull request closed without merging**
