### PR TITLE
Add windows support via precompiled libzmq.a

### PR DESCRIPTION
**Pull request by janschulz**
The way to rebuild the precompiled libraries is describe in
README.WIN.md.

See also #5 and https://github.com/takluyver/IRkernel/issues/54

Closes: #7

### CODE REVIEW

**Comment by JanSchulz** [comment]
If also added precompiled versions to my github page:

```
install.packages("drat")
drat:::add("janschulz") # this adds a new repository for at janschulz.github.io/drat/
install.packages("rzmq")
```

**Comment by takluyver** [comment]
We've just been talking with some of the open source people from Microsoft, which is buying Revolution Analytics. In a couple of weeks, someone there might be able to help with this.

**Comment by asmeurer** [comment]
This is working for me. I tried building rzmq using the instructions at http://blogs.msdn.com/b/gpalem/archive/2013/02/06/building-zeromq-for-r-rzmq-with-visual-studio-express-full.aspx, but I only got it to work on 32-bit Windows (64-bit Windows kept giving me "%1 Is Not a Valid Win32 Application").

**Comment by asmeurer** [comment]
By the way, if it helps, [nloptr](https://github.com/conda/conda-recipes/blob/master/r-packages/r-nloptr/install_windows.sh) is another package that has to link against a C library and is [difficult](https://github.com/jyypma/nloptr/blob/master/INSTALL.windows) to build on Windows.

**Comment by snoweye** [comment]
- I hope this help a little.
- pbdZMQ ships with zmq 4.1.0 rc1 and has 32/64 windows binary built with native Rtools. Binary can be download at http://thirteen-01.stat.iastate.edu/snoweye/pbdr/?item=download
- The source code under src/ contains how the zmq source is modified for Rtools for both i386 and x64.
- It will be sent to CRAN when its application pbdCS is ready. A simple tutorial for windows can be found at http://thirteen-01.stat.iastate.edu/snoweye/pbdr/?item=tutorial4

**Comment by armstrtw** [comment]
That looks great.  I guess I'm a little confused as to why you felt the need to re-implement the  low level zmq functions in your own package...

**Comment by JanSchulz** [comment]
Any news on integrating this PR? Currently the conda packages use these binaries on windows (via the PR branch in my repo)...

Instead of including precompiled binaries one could also include the relevant sources and compile that on windows (and mac?). This is similar to how RSQlite does it: https://github.com/rstats-db/RSQLite

**Comment by snoweye** [comment]
FYI https://cran.r-project.org/web/checks/check_results_pbdZMQ.html works for most platforms.
FYI https://cran.r-project.org/web/checks/check_results_rzmq.html works for Solaris as well.
See pbdZMQ vignettes for Solaris solutions.

**Pull request closed without merging**
